name: GCP_login
label: GCP Login

description: |
  This skillet will log into GCP. You will be prompted to follow a link and enter a device-code in your browser.
type: template

extends:

labels:
  collection: GCP Jenkins Security Framework

variables:
#  - name: api_key
#    description: API Key
#    default: abc123
#    type_hint: text

snippets:
  - name: script
    file: docker_cmd.j2
